### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by PhilCorcoran**
Allow a proxy to be passed in the options so it will work behind a firewall.
.pipe(w3cjs({
      proxy: 'http://proxy:8080'
    }));

### CODE REVIEW

**Comment by callumacrae** [comment]
Thanks. Would you also be able to add this to the readme?

**Comment by PhilCorcoran** [comment]
That update to the README is done

**Comment by callumacrae** [comment]
Thanks! I'll do a release later today: just got a couple other things I need to tidy up.

**Comment by PhilCorcoran** [comment]
Nice one. It'll help all the developers here to validate their html as part
of a build step
Cheers
Philip

**Comment by PhilCorcoran** [comment]
Hi Callum,
Can you publish this release to the npm registry?
thanks
Philip

**Comment by callumacrae** [comment]
Released with a couple other changes as 1.1.0: sorry for the delay!

**Comment by PhilCorcoran** [comment]
Works like a charm, thanks

**Pull request merged**
