### PR TITLE
Add optional reporter like CoffeeLint

### PR DESCRIPTION
**Pull request by haydenbleasel**

### CODE REVIEW

**Comment by callumacrae** [comment]
Good call! Would you be able to add a test for this?

Thanks for this :)

**Comment by haydenbleasel** [comment]
@callumacrae I would love to but I have no idea how to write these tests :S

**Comment by haydenbleasel** [comment]
Ping (sorry but I need this).

**Comment by callumacrae** [comment]
Sorry for the delay! Thoughts on #17?

**Comment by haydenbleasel** [comment]
Yeah, that works.

**Comment by callumacrae** [comment]
Released as 1.2.0, thank you! :tada:

**Pull request closed without merging**
