### PR TITLE
Documenting file.w3cjs

### PR DESCRIPTION
**Pull request by adam-lynch**
I was delighted to find this when having a look at `index.js`, but it's really too good of a feature not to be described in the readme :)

### CODE REVIEW

**Comment by callumacrae** [comment]
Sorry for the huuuge delay, that was not okay. Thanks for this!

Would you be able to update the example to use [through2].obj instead of event-stream? I'm updating the plugin itself now. I can do it if you don't want to :smiley: 

[through2]: http://npmjs.org/package/through2

**Comment by adam-lynch** [comment]
Sure, I'll do it when I get a chance :smile:

**Comment by adam-lynch** [comment]
Done

**Comment by callumacrae** [comment]
Thank you!

**Pull request merged**
